import type { SelectOption } from '../components/CustomSelect';

export const CATEGORIAS = [
  'Italiana',
  'Mexicana',
  'Asiática',
  'Japonesa',
  'China',
  'India',
  'Mediterránea',
  'Española',
  'Francesa',
  'Americana',
  'Latinoamericana',
  'Griega',
  'Árabe',
  'Postres',
  'Panadería',
  'Desayunos',
  'Sopas y Caldos',
  'Ensaladas',
  'Mariscos',
  'Carnes',
  'Vegana',
  'Vegetariana',
  'Sin Gluten',
  'Otra',
] as const;

export const DIFICULTADES = ['Fácil', 'Media', 'Difícil'] as const;

export const UNIDADES: SelectOption[] = [
  { value: '', label: 'Unidad' },
  { value: '__vol', label: 'Volumen', isGroup: true },
  { value: 'ml', label: 'ml' },
  { value: 'L', label: 'L' },
  { value: 'taza', label: 'taza' },
  { value: 'tazas', label: 'tazas' },
  { value: 'cucharada', label: 'cucharada' },
  { value: 'cucharadita', label: 'cucharadita' },
  { value: '__peso', label: 'Peso', isGroup: true },
  { value: 'g', label: 'g' },
  { value: 'kg', label: 'kg' },
  { value: 'lb', label: 'lb' },
  { value: 'oz', label: 'oz' },
  { value: '__conteo', label: 'Conteo', isGroup: true },
  { value: 'unidad', label: 'unidad' },
  { value: 'unidades', label: 'unidades' },
  { value: 'pieza', label: 'pieza' },
  { value: 'piezas', label: 'piezas' },
  { value: 'diente', label: 'diente' },
  { value: 'dientes', label: 'dientes' },
  { value: 'hoja', label: 'hoja' },
  { value: 'hojas', label: 'hojas' },
  { value: 'ramita', label: 'ramita' },
  { value: '__otros', label: 'Otros', isGroup: true },
  { value: 'al gusto', label: 'al gusto' },
  { value: 'pizca', label: 'pizca' },
  { value: 'puñado', label: 'puñado' },
  { value: 'manojo', label: 'manojo' },
  { value: 'rebanada', label: 'rebanada' },
  { value: 'rebanadas', label: 'rebanadas' },
  { value: 'trozo', label: 'trozo' },
  { value: 'trozos', label: 'trozos' },
  { value: 'lata', label: 'lata' },
  { value: 'paquete', label: 'paquete' },
];
